### ISSUE TITLE
Python TypeError: 'collections.OrderedDict' object is not callable

### ISSUE THREAD

**Issue by kjungw1025** [TABA-4th/taba-backend-flask#21]
1. 6개 모델을 가지고 분석을 진행했을 때 아래와 같은 오류 발생
이전에 낮은 정확도의 모델을 가지고 동일한 구조로 실행했을 때 문제 없이 동작하는 것으로 보아,
AI쪽 모델을 save하는 과정에서 기존과 다르게 진행한 것 같음

<br>
<img src="https://github.com/TABA-4th/taba-backend-flask/assets/120318020/029fd355-8879-45ff-af94-f7a89414883f">

<br><br>
관련 자료<br>
https://stackoverflow.com/questions/48419626/pytorch-cant-load-cnn-model-and-do-prediction-typeerror-collections-orderedd

**Comment by kolo4917** [comment]
1. AI 모델을 save하는 도중, state.dict를 저장하는 것과 model 저장 관련

※ 두 가지 방식이 존재하는데 각 모델마다 최적화 된 하이퍼 파라미터들이 다르고 transform, structure도 변형되었다.
-> 기존 : 서버에 efficient net으로 pretrain된 모델을 로드하고  state.dict를 로드하였다. 
-> 변경 : 다른 클래스를 가지고 있는 모델도 있기 때문에 서버에 6개의 모델을 직접 로드하는 방법으로 해결하였다.

<img width="470" alt="error" src="https://github.com/TABA-4th/taba-backend-flask/assets/117979078/aaf06221-1ea4-4d7e-8b19-538bc4bedf8d">

-> 유의점 : 모델이 많아지거나, 모델의 크기가 커지면 응답 속도 처리에 문제가 있을 수도 있지만, 우선은 모델의 크기가 작아 유의미한 응답 속도 차이는 없어보인다.
